anchor_version = "0.25.0"

[programs.localnet]
serum_swap = "BVCvLvqHbSsTZmaydjJhKAbvNrELdnaxipDk99SacFpt"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "BVCvLvqHbSsTZmaydjJhKAbvNrELdnaxipDk99SacFpt"
program = "/home/kishore/Desktop/swap/target/deploy/serum_swap.so"

[scripts]
test = "mocha -t 1000000 tests/"